<Project>
  <PropertyGroup>
    <BaseIntermediateOutputPath>$(TEMP)\ETMS_Solution\obj\$(MSBuildProjectName)\</BaseIntermediateOutputPath>
    <BaseOutputPath>$(TEMP)\ETMS_Solution\bin\$(MSBuildProjectName)\</BaseOutputPath>
    <DefaultItemExcludes>$(DefaultItemExcludes);$(MSBuildProjectDirectory)\obj\**;$(MSBuildProjectDirectory)\bin\**;$(MSBuildProjectDirectory)\artifacts\**</DefaultItemExcludes>
  </PropertyGroup>
</Project>
